### ISSUE TITLE
A malformed graph may raise ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by gfonsecabr** [MarioGrobler/ds_verifier#2]
The following line will raise an  ArrayIndexOutOfBoundsException when reading strings[1] if the graph has a line with "p" alone.

https://github.com/MarioGrobler/ds_verifier/blob/073605ded1eba84ea3bcd016282c0f82a6659e43/Dominating%20Set%20Verifier/src/main/java/de/uni/bremen/ds/io/Importer.java#L29

Since the line is supposed to test if the graph contains a "p ds" line, I believe you may want to fix that as:

if (strings.length < 2 ||  !strings[1].equals("ds")) {

**Comment by MarioGrobler** [comment]
fixed.
